name: ABlink - Messenger Shortcut
description: 🚀 Simplify sharing with dynamic shortcuts and seamless user experience.
full_description: '<b>v1.0.1 (Dec 17, 2024)</b><br>
<br>- Add Contacts as Widgets on the Home screen for faster access and a better experience.
<br>- Customize the widget view by removing the ABlink app icon for a cleaner visualization.
<br>

<b>v1.0.0 (Dec 11, 2024)</b><br>
<br>- Initial release of ABlink - Your shortcut to seamless sharing.
<br>- Create, customize, and manage dynamic shortcuts for quick access.
<br>- Integrated with a clean and intuitive UI for smooth navigation.
<br>- Support for in-app purchases to unlock additional shortcut slots.
<br>- Personalized shortcut options with editable names and avatars.
<br>- Improved sharing experience through pre-defined content and deep linking.
<br>
<br>Thank you for choosing ABlink! More features are coming soon!'
android: https://play.google.com/store/apps/details?id=com.devindie.directsharemessenger
iOS: false
web: false

screenshots:
  - image1.jpeg
  - 01-screenshot.jpeg
  - 02-screenshot.jpeg
  - 03-screenshot.jpeg
  - 04-screenshot.jpeg
producthunt: false
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
